services:
  - type: web
    name: data-quality-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app6:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: GROQ_API_KEY
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: SHAREPOINT_SITE_URL
        sync: false
      - key: SHAREPOINT_SHARE_URL
        sync: false